import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'screens/activation_screen.dart';
import 'services/app_state.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Requires platform config files generated by `flutterfire configure`
  // pointing at your Firebase project (see backend README). Licensing
  // features are skipped gracefully if this fails, e.g. during early
  // local development before the backend is set up.
  try {
    await Firebase.initializeApp();
  } catch (_) {}
  runApp(const PanchapakshiApp());
}

class PanchapakshiApp extends StatelessWidget {
  const PanchapakshiApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => AppState(),
      child: MaterialApp(
        title: 'கோழி பட்சி',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          colorSchemeSeed: const Color(0xFF6A1B9A),
          useMaterial3: true,
          fontFamily: 'NotoSansTamil', // add font asset — see README
        ),
        home: const ActivationScreen(),
      ),
    );
  }
}
